[build]
nixpacksVersion = 1

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python3 -m venv venv",
  ". venv/bin/activate",
  "venv/bin/pip install --upgrade pip",
  "venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "venv/bin/python main.py"
