[build]
nixpacksVersion = 1

[phases.setup]
nixPkgs = ["python311Full"]

[phases.install]
cmds = [
  "python3 -m ensurepip",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements.txt"
]

[start]
cmd = "python3 main.py"
